backend:
  name: bitbucket
  repo: ascension-cloud-solutions/landing_page
  branch: master
  auth_type: oauth

media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "blogs"
    label: "Blogs"
    folder: "src/blog-posts"
    create: true
    slug: "{{year}}-{{month}}-{{date}}-{{slug}}"
    feilds: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "date", name: "date", widget: "dateTime" }
      - { label: "Tags", name: "image", widget: "list", default: ["post"]}
      - { label: "Feature Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }